const GeoLayout vr_fire_flower_geo[] = {
    GEO_CULLING_RADIUS(600),
    GEO_OPEN_NODE(),
        GEO_BILLBOARD(),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_ALPHA, vr_fire_flower_dl),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout vr_fireball_geo[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(LAYER_TRANSPARENT + 3, geo_vr_fireball_color),
        GEO_BILLBOARD(),
        GEO_OPEN_NODE(),
            GEO_SWITCH_CASE(8, geo_switch_anim_state),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_0_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_1_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_2_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_3_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_4_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_5_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_6_dl),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_fireball_frame_7_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout vr_rasengan_geo[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(LAYER_TRANSPARENT + 3, geo_vr_rasengan_color),
        GEO_ASM(0, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_rasengan_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(LAYER_TRANSPARENT + 3, geo_vr_rasengan_color),
        GEO_ASM(1, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 0, 90, 45),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_rasengan_dl),
        GEO_CLOSE_NODE(),
        // Three close-fitting tornado-crown rings. Their different planes
        // become independently visible as the parent orb spins on all axes.
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(2, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 12, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 65536,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(3, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 58, 31, 17),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 68813,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(4, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, -39, 67, -24),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 72090,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        // These three additional rings are hidden for a held Rasengan and
        // enabled only while the Rasen Shuriken explosion bubble exists.
        GEO_ASM(1, geo_vr_rasengan_ring_color),
        GEO_ASM(6, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 29, -52, 71),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 75367,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(2, geo_vr_rasengan_ring_color),
        GEO_ASM(7, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, -63, 19, 48),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 78643,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(3, geo_vr_rasengan_ring_color),
        GEO_ASM(8, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 44, 76, -57),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 81920,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};

const GeoLayout vr_rasen_shuriken_geo[] = {
    GEO_NODE_START(),
    GEO_OPEN_NODE(),
        GEO_ASM(LAYER_TRANSPARENT + 3, geo_vr_rasengan_color),
        GEO_ASM(0, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 0, 0, 0),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_rasengan_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(LAYER_TRANSPARENT + 3, geo_vr_rasengan_color),
        GEO_ASM(1, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 0, 90, 45),
        GEO_OPEN_NODE(),
            GEO_DISPLAY_LIST(LAYER_TRANSPARENT, vr_rasengan_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(2, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 12, 0, 0),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 65536,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(3, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 58, 31, 17),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 68813,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(0, geo_vr_rasengan_ring_color),
        GEO_ASM(4, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, -39, 67, -24),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 72090,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        // Rings four through six appear progressively while charging and
        // remain present through the fully charged projectile and explosion.
        GEO_ASM(1, geo_vr_rasengan_ring_color),
        GEO_ASM(6, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 29, -52, 71),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 75367,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(2, geo_vr_rasengan_ring_color),
        GEO_ASM(7, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, -63, 19, 48),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 78643,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_ASM(3, geo_vr_rasengan_ring_color),
        GEO_ASM(8, geo_vr_rasengan_visual_spin),
        GEO_ROTATION_NODE(0x00, 44, 76, -57),
        GEO_OPEN_NODE(),
            GEO_SCALE_WITH_DL(LAYER_TRANSPARENT, 81920,
                vr_rasengan_tornado_ring_dl),
        GEO_CLOSE_NODE(),
        GEO_BILLBOARD(),
        GEO_OPEN_NODE(),
            GEO_ASM(LAYER_TRANSPARENT + 3,
                geo_vr_rasen_shuriken_color),
            GEO_ASM(5, geo_vr_rasengan_visual_spin),
            GEO_ROTATION_NODE(0x00, 0, 0, 0),
            GEO_OPEN_NODE(),
                GEO_DISPLAY_LIST(LAYER_TRANSPARENT,
                    vr_rasen_shuriken_dl),
            GEO_CLOSE_NODE(),
        GEO_CLOSE_NODE(),
    GEO_CLOSE_NODE(),
    GEO_END(),
};
